version: "3.5"

services: 
    suporte_db:
        container_name: suporte_db
        image: mysql:5.5.44
        working_dir: /var/lib/mysql/data
        volumes:
            - /var/lib/mysql/data
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}